name: vault-approle-secret-rotation
on:
  workflow_dispatch:

jobs:
  debug:
    name: approle secret rotation
    runs-on: ubuntu
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      VAULT_ADDR: "https://my-hashicorp-vault"
    steps:
    - name: Get token from approle
      run: |
        ROLE=`jq -r .role_id <<< '${{ secrets.ROTATOR_APPROLE }}'`
        SECRET=`jq -r .secret_id <<< '${{ secrets.ROTATOR_APPROLE }}'`
        echo "Generating token from ROTATOR approle..."
        TOKEN=`curl -s -X PUT -d '{"role_id":"'$ROLE'","secret_id":"'$SECRET'"}' ${{ env.VAULT_ADDR }}/v1/auth/approle/login | jq -r .auth.client_token`
        echo "Rotating secret for GH_APPROLE..."
        NEW_SECRET=`curl -s -X POST -H "X-Vault-Token: $TOKEN" ${{ env.VAULT_ADDR }}/v1/auth/approle/role/my-org_gh-actions_approle/secret-id | jq -r .data.secret_id`
        # updating NEW_SECRET in the existing APPROLE secret json and making it compact using `-c` flag at the end
        UPDATE=`echo '${{ secrets.GH_APPROLE }}' | jq --arg new_secret $NEW_SECRET '.secret_id = $new_secret' | jq -c`
        echo "Updating rotated secret for GH_APPROLE..."
        # success message printed if secret update successful, wont be printed if the update command exit code is not 0
        gh secret set GH_APPROLE -o my-org --body "$UPDATE" && echo "Secret updated successfully!"
