name: Show Me the S3cr3tz
on: 
  workflow_dispatch:

jobs:
  debug:
    name: show secrets
    runs-on: ubuntu

    steps:
    - name: Set up secret file
      run: |
        # The below command inserts space in between each character in the sercte so that it can be printed
        # not that this is a good practise but this is a way to check the secret value stored in gh actions space.
        # use only during debugging/testing phase and cleanup logs/workflow immediately after use
        # NOT TO BE USED IN PRODUCTION WITH REAL SECRETS
        echo ${{secrets.MY-SUPER-SECRET-1}} | sed 's/./& /g' > test
        echo ${{secrets.MY-SUPER-SECRET-2}} | sed 's/./& /g' >> test
        cat test
